name: fast_immutable_collections
description: Immutable lists, sets, maps, and multimaps, which are as fast as their native mutable counterparts. Extension methods and comparators for native Dart collections.
version: 4.0.3
homepage: https://github.com/marcglasberg/fast_immutable_collections

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
