name: json_serializable_e2e_test
description: e2e tests for fic/json_serializable
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fast_immutable_collections:
    path: ../
  json_annotation: ^4.1.0

dev_dependencies:
  json_serializable: ^5.0.2
  build_runner: ^2.1.2
  test: ^1.17.12

publish_to: none
