name: benchmark_app
description: The example project for the fast_immutable_collections package.
publish_to: "none"
version: 0.0.1

environment:
  flutter: ">=2.0.0 <=3.0.0"
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.10.0
  intl: ^0.17.0

  fast_immutable_collections_benchmarks:
    path: ../

dev_dependencies:
  pedantic: ^1.11.0
